/**
 * Build an OpenWrt .apk package (apk-tools v3, OpenWrt 24.10+/25).
 *
 * Preferred path: the real `apk mkpkg` from apk-tools 3, which produces a
 * genuine APKv3 package and is what the GitHub Actions runner uses.
 *
 * Local path: when apk-tools is not installed, a spec-conformant APKv2 is
 * assembled directly (gzip tar of /scripts + /data with a .PKGINFO header),
 * so the packaging can still be exercised off-device. Pass --require-apk to
 * make the absence of apk-tools a hard error instead.
 *
 *   node scripts/build-apk.js
 */
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const { tarGz, rmrf, copyDir, applyModes } = require('./lib/tar');

const ROOT = path.resolve(__dirname, '..');
const DATA = path.join(ROOT, 'package/data');
const CONTROL = path.join(ROOT, 'package/control');
const pkg = require(path.join(ROOT, 'package.json'));

const NAME = pkg.name;
const ARCH = 'noarch';
const STAGE = path.join(ROOT, '.apkstage');
const DIST = path.join(ROOT, 'dist');
const REQUIRE_APK = process.argv.includes('--require-apk');

// APK versions use "x.y.z-rN".
const base = pkg.version;
const VERSION = /-r\d+$/.test(base) ? base : `${base}-r1`;
const OUT = path.join(DIST, `${NAME}-${VERSION}.apk`);

function controlField(text, key) {
    const m = text.match(new RegExp(`^${key}: *(.*)$`, 'm'));
    return m ? m[1].trim() : '';
}

function controlFieldMultiline(text, key) {
    const lines = text.split(/\r?\n/);
    const out = [];
    let capturing = false;
    for (const line of lines) {
        if (capturing) {
            if (/^\s+\S/.test(line)) out.push(line.trim());
            else break;
        } else if (new RegExp(`^${key}:`).test(line)) {
            capturing = true;
            const rest = line.slice(line.indexOf(':') + 1).trim();
            if (rest) out.push(rest);
        }
    }
    return out.join(' ');
}

function executable(rel) {
    return (
        rel.startsWith('etc/init.d/') ||
        rel.startsWith('usr/sbin/') ||
        rel.startsWith('usr/bin/') ||
        rel.startsWith('usr/lib/oui-httpd/rpc/') ||
        rel.endsWith('.sh')
    );
}

function stageData() {
    rmrf(STAGE);
    fs.mkdirSync(STAGE, { recursive: true });
    copyDir(DATA, path.join(STAGE, 'data'));
    fs.mkdirSync(path.join(STAGE, 'scripts'), { recursive: true });
    for (const [apkName, ipkName] of [
        ['post-install', 'postinst'],
        ['pre-deinstall', 'prerm'],
        ['post-deinstall', 'postrm'],
    ]) {
        const src = path.join(CONTROL, ipkName);
        if (fs.existsSync(src)) {
            const dst = path.join(STAGE, 'scripts', apkName);
            fs.copyFileSync(src, dst);
            fs.chmodSync(dst, 0o755);
        }
    }
}

function tryMkpkg(controlText) {
    const apkBin = process.env.APK || 'apk';
    const args = ['mkpkg'];
    args.push('--info', `name:${NAME}`);
    args.push('--info', `version:${VERSION}`);
    const desc = controlFieldMultiline(controlText, 'Description').replace(/\s+/g, ' ').trim();
    if (desc) args.push('--info', `description:${desc}`);
    args.push('--info', `arch:${ARCH}`);
    args.push('--info', `origin:${NAME}`);
    const maint = controlField(controlText, 'Maintainer');
    if (maint) args.push('--info', `maintainer:${maint}`);
    const license = controlField(controlText, 'License') || 'MIT';
    args.push('--info', `license:${license}`);
    for (const s of fs.readdirSync(path.join(STAGE, 'scripts'))) {
        args.push('--script', `${s}:${path.join(STAGE, 'scripts', s)}`);
    }
    args.push('--files', path.join(STAGE, 'data'));
    args.push('--output', OUT);

    execFileSync(apkBin, args, { stdio: 'inherit' });
    return true;
}

/** Assemble a spec-conformant APKv2 (gzip tar of /scripts, /data, .PKGINFO). */
function buildApkV2(controlText) {
    const tmp = path.join(ROOT, '.apkv2');
    rmrf(tmp);
    fs.mkdirSync(tmp, { recursive: true });

    const desc = controlFieldMultiline(controlText, 'Description').replace(/\s+/g, ' ').trim();
    const depends = controlField(controlText, 'Depends')
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean)
        .join(' ');

    const pkginfo = [
        '# Generated by scripts/build-apk.js',
        `pkgname = ${NAME}`,
        `pkgver = ${VERSION}`,
        `pkgdesc = ${desc}`,
        `url = ${controlField(controlText, 'Homepage') || ''}`,
        `builddate = ${Math.floor(Date.now() / 1000)}`,
        `packager = ${controlField(controlText, 'Maintainer') || 'unknown'}`,
        `size = ${dirSize(path.join(STAGE, 'data'))}`,
        `arch = ${ARCH}`,
        `origin = ${NAME}`,
        `license = ${controlField(controlText, 'License') || 'MIT'}`,
        ...(depends ? [`depend = ${depends}`] : []),
        'datahash = ',
        '',
    ].join('\n');

    fs.writeFileSync(path.join(tmp, '.PKGINFO'), pkginfo);

    const tree = path.join(ROOT, '.apkv2tree');
    rmrf(tree);
    fs.mkdirSync(tree, { recursive: true });
    fs.writeFileSync(path.join(tree, '.PKGINFO'), pkginfo);
    copyDir(path.join(STAGE, 'data'), path.join(tree, 'data'));
    if (fs.existsSync(path.join(STAGE, 'scripts'))) {
        copyDir(path.join(STAGE, 'scripts'), path.join(tree, 'scripts'));
    }

    // Modes must be recorded explicitly: the RPC object has to arrive executable,
    // and on Windows neither chmod nor bsdtar can express that. The manual writer
    // in lib/tar applies this mapping; GNU tar uses the on-disk modes instead.
    applyModes(path.join(tree, 'data'), executable);
    tarGz(tree, OUT, (rel) => {
        const r = rel.replace(/^data\//, '');
        if (r.startsWith('scripts/') || r.startsWith('.')) return 0o755;
        return executable(r) ? 0o755 : 0o644;
    });
    rmrf(tmp);
    rmrf(tree);
}

function dirSize(dir) {
    let total = 0;
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
        const p = path.join(dir, e.name);
        total += e.isDirectory() ? dirSize(p) : fs.statSync(p).size;
    }
    return total;
}

// ---- go ------------------------------------------------------------------
fs.mkdirSync(DIST, { recursive: true });
execFileSync(process.execPath, [path.join(ROOT, 'scripts/build-ui.js')], { stdio: 'inherit' });
stageData();

const controlText = fs.readFileSync(path.join(CONTROL, 'control'), 'utf8');
let usedApk = false;
try {
    usedApk = tryMkpkg(controlText);
} catch (e) {
    if (REQUIRE_APK) {
        console.error(
            "'apk mkpkg' unavailable (apk-tools v3 required, e.g. Alpine 3.23+). " +
            'Set APK=/path/to/apk, or run on GitHub Actions.'
        );
        rmrf(STAGE);
        process.exit(1);
    }
    console.warn('apk-tools not found; assembling an APKv2 container locally instead');
}

if (!usedApk) buildApkV2(controlText);

rmrf(STAGE);
console.log(
    `built ${path.relative(ROOT, OUT)}  ${(fs.statSync(OUT).size / 1024).toFixed(1)} KB` +
    (usedApk ? '  (apk-tools v3)' : '  (APKv2 fallback)')
);
