/**
 * Build the GL.iNet SDK4 view bundle.
 *
 * CONTRACT (reverse-engineered from the first-party views on the device):
 *
 *     const code = (await axios.get('/views/gl-sdk4-ui-<view>.common.js')).data
 *     component = eval(code)
 *     to.matched[index].components.default = component
 *
 * Two consequences:
 *   1. the SDK requests the *uncompressed* .js path, so the .js must exist for
 *      nginx's gzip_static to serve the .gz alongside it; and
 *   2. the value of the evaluated program must BE the component object.
 *
 * GL's own bundles are webpack builds whose last statement evaluates to the
 * entry's `exports.default`. We reproduce that shape deterministically by
 * stripping webpack's `module.exports = ...` assignment and wrapping the whole
 * bundle in a function that returns `__webpack_exports__.default`. Using
 * webpack's `library` option instead would yield a Module wrapper, which the
 * SDK would mount as an empty component.
 *
 * GL ships a runtime-only Vue build (no template compiler), so templates are
 * compiled to render functions at build time by vue-loader 15 with
 * vue-template-compiler pinned to GL's exact Vue version (2.6.12).
 */
const fs = require('fs');
const path = require('path');
const webpack = require('webpack');
const { VueLoaderPlugin } = require('vue-loader');
const { gzipFile } = require('./lib/gzip');

const OUT_DIR = path.resolve(__dirname, '../package/data/www/views');
const VIEW_NAME = 'gl-ai';

/** Global webpack exposes the entry's exports on. Namespaced to avoid clashes. */
const LIB_NAME = 'GL_AI_VIEW_BUNDLE';

const config = {
    mode: 'production',
    entry: path.resolve(__dirname, '../src/ui/index.js'),
    target: ['web', 'es5'],
    output: {
        path: OUT_DIR,
        filename: `gl-sdk4-ui-${VIEW_NAME}.common.js`,
        // Expose the entry's named exports on window[LIB_NAME]. The bundle is
        // then wrapped so eval() yields `default` directly.
        library: { name: LIB_NAME, type: 'window' },
    },
    module: {
        rules: [
            { test: /\.vue$/, loader: 'vue-loader' },
            { test: /\.css$/, use: ['vue-style-loader', 'css-loader'] },
        ],
    },
    plugins: [
        new VueLoaderPlugin(),
        new webpack.optimize.LimitChunkCountPlugin({ maxChunks: 1 }),
    ],
    resolve: {
        extensions: ['.js', '.vue', '.json'],
        alias: { vue$: 'vue/dist/vue.runtime.esm.js' },
    },
    performance: { hints: false },
    devtool: false,
    stats: { preset: 'errors-warnings' },
};

/**
 * Wrap webpack's output so the evaluated program IS the component.
 *
 * The result must not depend on `module`, `exports`, `require` or any webpack
 * internal: the page the SDK evals this in provides none of them (verified in
 * a real browser). So we keep the bundle verbatim inside an IIFE and read the
 * component back off the global that `output.library` publishes.
 */
function toSdkShaped(code) {
    return (
        `/* GL-AI助手 view bundle - generated by scripts/build-ui.js. ` +
        `Do not edit; see scripts/build-ui.js for the SDK loader contract. */\n` +
        `(function(){var module={exports:{}};var exports=module.exports;\n` +
        code +
        `\nvar v=Object.prototype.hasOwnProperty.call(window,'${LIB_NAME}')` +
        `?window['${LIB_NAME}']:null;` +
        `try{delete window['${LIB_NAME}']}catch(e){window['${LIB_NAME}']=undefined}\n` +
        `if(!v)throw new Error('GL-AI view bundle did not register');\n` +
        `return (v&&v.__esModule&&v.default)?v.default:(v.default||v)})();`
    );
}

webpack(config, (err, stats) => {
    if (err) {
        console.error(err.stack || err);
        process.exit(1);
    }
    const info = stats.toJson();
    if (stats.hasErrors()) {
        console.error(info.errors.map((e) => e.message || e).join('\n'));
        process.exit(1);
    }
    if (stats.hasWarnings()) {
        console.warn(info.warnings.map((w) => w.message || w).join('\n'));
    }

    const outFile = path.join(config.output.path, config.output.filename);
    const code = toSdkShaped(fs.readFileSync(outFile, 'utf8'));
    fs.writeFileSync(outFile, code);

    const gz = gzipFile(outFile);
    console.log(
        `built ${path.relative(process.cwd(), outFile)}  ` +
        `${(Buffer.byteLength(code) / 1024).toFixed(1)} KB ` +
        `(gz ${(gz.size / 1024).toFixed(1)} KB)`
    );
});
